### PR TITLE
NEW Update singular and plural names

### PR DESCRIPTION
**Pull request by emteknetnz**
Tweak for https://github.com/silverstripeltd/product-issues/issues/222

### CODE REVIEW

**Comment by robbieaverill** [comment]
I can't see the issue you referenced, but this is an enhancement as it was originally designed this way. Please target a minor release branch.

_Edit:_ just noting that while the source translation is changing, I think it's less likely to affect non-English languages because it is adding _more_ context to the existing noun (fine this way, doesn't need a new key).

**Comment by emteknetnz** [comment]
@robbieaverill done

Note there wasn't previously a `2` branch, I chatted with Garion and he agreed we should create a `2` branch off master to match conventions on other supported modules

I've created another pull request to update config https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/16

**Comment by robbieaverill** [comment]
Nice, you could update your commit message too if you wanted to be semantically correct

**Comment by emteknetnz** [comment]
Have changed 'FIX' to 'API' in the commit message

**Comment by robbieaverill** [comment]
😄 it's more of an enhancement than an API change

**Comment by emteknetnz** [comment]
Have changed 'API' to 'NEW' :-)

**Review by maxime-rainville — APPROVED** [review]

**Pull request merged**
